name: w2b_flutter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # flutter_native_splash: ^2.4.0
  geolocator: ^12.0.0
  google_maps_flutter: ^2.6.1
  permission_handler: ^11.3.1
  dio: ^5.9.0
  retrofit: ^4.5.0
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.10+1
  flutter_secure_storage: ^9.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.8.0
  retrofit_generator: ^8.2.1
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/